require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HousesController do

  # This should return the minimal set of attributes required to create a valid
  # House. As you add validations to House, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HousesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all houses as @houses" do
      house = House.create! valid_attributes
      get :index, {}, valid_session
      assigns(:houses).should eq([house])
    end
  end

  describe "GET show" do
    it "assigns the requested house as @house" do
      house = House.create! valid_attributes
      get :show, {:id => house.to_param}, valid_session
      assigns(:house).should eq(house)
    end
  end

  describe "GET new" do
    it "assigns a new house as @house" do
      get :new, {}, valid_session
      assigns(:house).should be_a_new(House)
    end
  end

  describe "GET edit" do
    it "assigns the requested house as @house" do
      house = House.create! valid_attributes
      get :edit, {:id => house.to_param}, valid_session
      assigns(:house).should eq(house)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new House" do
        expect {
          post :create, {:house => valid_attributes}, valid_session
        }.to change(House, :count).by(1)
      end

      it "assigns a newly created house as @house" do
        post :create, {:house => valid_attributes}, valid_session
        assigns(:house).should be_a(House)
        assigns(:house).should be_persisted
      end

      it "redirects to the created house" do
        post :create, {:house => valid_attributes}, valid_session
        response.should redirect_to(House.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved house as @house" do
        # Trigger the behavior that occurs when invalid params are submitted
        House.any_instance.stub(:save).and_return(false)
        post :create, {:house => {}}, valid_session
        assigns(:house).should be_a_new(House)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        House.any_instance.stub(:save).and_return(false)
        post :create, {:house => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested house" do
        house = House.create! valid_attributes
        # Assuming there are no other houses in the database, this
        # specifies that the House created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        House.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => house.to_param, :house => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested house as @house" do
        house = House.create! valid_attributes
        put :update, {:id => house.to_param, :house => valid_attributes}, valid_session
        assigns(:house).should eq(house)
      end

      it "redirects to the house" do
        house = House.create! valid_attributes
        put :update, {:id => house.to_param, :house => valid_attributes}, valid_session
        response.should redirect_to(house)
      end
    end

    describe "with invalid params" do
      it "assigns the house as @house" do
        house = House.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        House.any_instance.stub(:save).and_return(false)
        put :update, {:id => house.to_param, :house => {}}, valid_session
        assigns(:house).should eq(house)
      end

      it "re-renders the 'edit' template" do
        house = House.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        House.any_instance.stub(:save).and_return(false)
        put :update, {:id => house.to_param, :house => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested house" do
      house = House.create! valid_attributes
      expect {
        delete :destroy, {:id => house.to_param}, valid_session
      }.to change(House, :count).by(-1)
    end

    it "redirects to the houses list" do
      house = House.create! valid_attributes
      delete :destroy, {:id => house.to_param}, valid_session
      response.should redirect_to(houses_url)
    end
  end

end
